name: Unhash
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        env:
          GOCOVEROUT: build/coverage.out
        run: |
          make generate format
          git diff --exit-code || (echo -e "::error::Run make generate format and commit changes\e[0m" && exit 1)
          make lint
          make integration-test coverage

      - name: Coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: build/coverage.out
          report: true
          chart: true
          amend: true
        if: github.event_name == 'push'
        continue-on-error: true
